CREATE TABLE songs (
  id INT AUTO_INCREMENT PRIMARY KEY,

  spotify_id VARCHAR(100) NOT NULL UNIQUE,

  title VARCHAR(255) NOT NULL,

  artist_id VARCHAR(100) NULL,
  artist_name VARCHAR(255) NOT NULL,

  album_id VARCHAR(100) NULL,
  album_name VARCHAR(255) NULL,
  album_image_url TEXT NULL,

  duration_ms INT NOT NULL,
  explicit BOOLEAN NOT NULL DEFAULT FALSE,

  spotify_url TEXT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);